language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

before_install:
  - go get -t -v ./...

script:
  - make vet
  - make fmt-check
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)